### ISSUE TITLE
Tags & releases

### ISSUE THREAD

**Issue by tomitzel** [ElasticEmail/elasticemail-php#1]
Could you please release at least a version (tag) here in GitHub? We cannot use the library in projects that have minimum-stability `stable`.
I see library is already at version 4.0.x, but its not reflected here and it makes it hard to work with it.

**Comment by ElasticEmail** [comment]
@tomitzel sure, we will do this in forthcoming days

**Comment by ElasticEmail** [comment]
From now on we will be adding tags with version number.
