### ISSUE TITLE
Missing API features

### ISSUE THREAD

**Issue by jurgenhaas** [ElasticEmail/elasticemail-php#3]
We're currently in the process of updating the Drupal integration with ElasticEmail and one part is to use this library instead of writing all ourselves.

However, we're missing some important API features like e.g. `Account/Load` and others with regard to statistics and logs.

Are they really missing in the library or have they been hidden so well?

**Comment by radzawee** [comment]
We support only selected range of features in public APIs. You can check them out in API documentation on our website. 
Also this library is implementing API v4 only.

**Comment by radzawee** [comment]
@jurgenhaas please ask [ElasticEmail support](https://elasticemail.com/contact), they will be glad to answer all your questions.

**Comment by jurgenhaas** [comment]
So, their support is not listening here? What's the purpose of this repository if they don't participate?

I wanted to be helpful, but I'm not prepared to take the extra effort to try and deliver helpful inputs on various places.

**Comment by aniakawa** [comment]
Hi @jurgenhaas! Anna from Elastic Email here.
This repository's purpose is to share code files made by our developers and collaborate with others if necessary. GitHub is an excellent place for developers to social network, but our Support team operates on a different channel. 
Regarding your request, you can email support@elasticemail.com (the same way you would write a comment here :) ), and our friendly team will review your message as soon as possible. We're not a typical "we'll respond to you within a working day" kind of support—we're available 24/7, so you can be sure you'll get a response within minutes.

We are looking forward to chatting with you via email!

**Comment by jurgenhaas** [comment]
Thanks @aniakawa well, I'm not a customer of ElasticEmail, I'm not even using your services. I'm just a developer who maintains the integration of this package with Drupal. As your API is limited, I thought I'd suggest the extension to support more features. You can let your internal team know about it. If this won't be made available, that's OK with me. Again, I'm not using it in the first place, I'm just integrating what's available.
