### ISSUE TITLE
Getting access denied in response

### ISSUE THREAD

**Issue by GaneshKandu** [ElasticEmail/elasticemail-php#5]
Hi,

I am trying to make a call on https://api.elasticemail.com/v2/email/send

but getting ``access denied`` on production server but same code is working on my local.

what could be issue ?

**Comment by ElasticEmail** [comment]
@GaneshKandu this library is related to v4 api [(docs)](https://elasticemail.com/developers/api-documentation/rest-api#tag/Emails), you are referring to v2 which is currently deprecated. Anyhow access denied usually means you don't have required Access Levels on your account to perform such action.

**Comment by ElasticEmail** [comment]
@GaneshKandu It is hard to tell without any additional info (most likely it's a lack of permissions on your Elastic Email account or API key that you are using), I recommend you write to our technical support via our website.
