### ISSUE TITLE
 Uncaught Error: Object of class ElasticEmail\Model\EventType could not be converted to string invendor/guzzlehttp/psr7/src/Query.php:104

### ISSUE THREAD

**Issue by oleksandr-mykhailenko** [ElasticEmail/elasticemail-php#6]
When I try to use example of Events Get from your document I get next error

**Comment by TomasoAlpaka** [comment]
I have encountered the same problem with _**EventsApi::eventsGet()**_

In your example and paramter description on https://github.com/ElasticEmail/elasticemail-php/blob/master/docs/Api/EventsApi.md#eventsget is written to send objects as parameters to your API.  
Also in EventsApi methods annotation. _E.g.: @parameters EventType[] $event_types – Types of Events to return_

But when they go through to Guzzle method _Query::build()_, strings are expected Uncaught Error is encountered. 

Workaround is to send strings to e.g. _EventsApi::eventsGet()_, but it does not look reliably and violates your annotaions.

I am using Elasticemail 4.0.22 and Guzzle 7.8

**Comment by radzawee** [comment]
We have updated our library using the latest OpenAPI Generator, version 7.7.0.
