### ISSUE TITLE
ElasticEmail\Api\listsByListnameContactsGet() ignores parameter "offset"

### ISSUE THREAD

**Issue by TomasoAlpaka** [ElasticEmail/elasticemail-php#8]
Newly added endpoint for contact retrieval from a given list ignores parameter _offset_.
Parameter _limit_ works.

This always find first page (like offset is 0):
1) Call via browser GET: https://api.elasticemail.com/v4/lists/{$listName}/contacts?apiKey={$key}&limit=100&offset=2
2) Call via this SDK: listsByListnameContactsGet($listName, $limit, $offset)

**Comment by DaweTaller** [comment]
Any updates here? It would be nice if it works...
